# FROM karelbemelmans/pipelines-hugo
FROM unibet/docker-centos-example-builder
MAINTAINER mail@karelbemelmans.com

COPY ./docker-build/run.sh /run.sh

VOLUME /src /output

WORKDIR /src
CMD ["/run.sh"]
